### ISSUE TITLE
applications.yaml different syntaxes

### ISSUE THREAD

**Issue by DuncanNaves** [upsun/convsun#5]
ConvSun ends up on a memory error when trying to convert an applications.yaml file with applications directly declared like follows:
```
drupalbackend:
  relationships: ~~~~~~
  mounts: ~~~~~
drupalfrontend:
  relationships:~~~~
```

As opposed to:
```
- name: drupalbackend
  relationships: ~~~~~~
  mounts: ~~~~~
-name: drupalfrontend
  relationships:~~~~
```
